version: 2

sources:
  - name: raw
    schema: raw_data_retail
    tables:
      - name: store
        identifier: stores_data_set
      - name: feature
        identifier: features_data_set
      - name: sales
        identifier: sales_data_set